# ==========================================
# Filebeat Helm Values - ECK integration
# ==========================================

filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        paths:
          - /var/lib/docker/containers/*/*.log
        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
                - logs_path:
                    logs_path: "/var/lib/docker/containers/"

    # ---- Output to Elasticsearch ----
    output.elasticsearch:
      hosts: ["https://elasticsearch-es-http:9200"]
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      ssl:
        certificate_authorities: ["/mnt/elastic/ca.crt"]

# ---- Environment variables ----
extraEnvs:
  - name: ELASTICSEARCH_USERNAME
    value: "elastic"
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-es-elastic-user
        key: elastic
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName

# ---- Mount Elasticsearch CA cert ----
extraVolumes:
  - name: elastic-certs
    secret:
      secretName: elasticsearch-es-http-ca-internal
      items:
        - key: tls.crt
          path: ca.crt

extraVolumeMounts:
  - name: elastic-certs
    mountPath: /mnt/elastic
    readOnly: true
