apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - elasticsearch-deployment.yaml
  - logstash-deployment.yaml
  - logstash-configmap.yaml
  - kibana-deployment.yaml
  - elk-ingress.yaml
